### ISSUE TITLE
Local/Dev env issues

### ISSUE THREAD

**Issue by yespbs** [davidsosavaldes/Attire#1]
I just downloaded Attire today for testing and really liked it. It worked like a charm ( and that reading the basic install doc )

However I found 3 small issues and like to mention.

1. the cache path for Sprockets\Cache is default set for /cache/file....css|js and only when uploaded to production with document root / or running in built php server php -S localhost:5000 works! but custom install dir ( localhost/myproject/ci_new/cache/.... ) does not work
  I searched and could update the application/libraries/attire/Attire.php line 663

  `before: $cache = '/'.$this->_cache_base.basename((string) $cache);`

  `updated: $cache = site_url('/'.$this->_cache_base.basename((string) $cache)); `

  This allows any environment to load the css / js perfectly. 
  Could you add that to core?
2. I am using default bootstrap theme but the theme master.twig in themes/bootstrap/master.twig is never loaded!! it always loads the libraries/attire/dist/template/master.twig
  I find no config for that!! could you check if this can be fixed
3. Twig issue, my other twig cache folder runs perfectly but Attrire does not write to cache folder even when its writable, not sure what is missing

Great work anyway

**Comment by davidsosavaldes** [comment]
Hello @yespbs and thank you for open this issue, i already fix this bugs according to your report.

1. Update the cache custom install dir with the CI URL helper function **base_url** because **site_url** doesn't work with virtualhost environments.
2. Attire now append Instead of prepend the default master template path (libraries/attire/dist/template/master.twig), this fix the problem with the master template in the bootstrap theme.
3. If you want to use the twig cache you need to pass as a second parameter in the set_theme() method like: 
`
    $this->attire
        ->set_theme('bootstrap', array('cache' => APPPATH.'cache/'))
`

**Comment by yespbs** [comment]
Hi @davidsosavaldes many thanks for the quick response. I have updated and all things work perfectly now. Thanks for this brilliant package.
